# Generated by Django 5.0.6 on 2026-05-20 21:50

import apps.tenancy.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customers', to='billing.priceplan')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(default=apps.tenancy.models._new_api_key_prefix, max_length=12, unique=True)),
                ('key_hash', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='api_keys', to='tenancy.customer')),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='tenancy.customer')),
            ],
            options={
                'db_table': 'customer_user',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['status'], name='customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['customer', 'revoked_at'], name='apikey_customer_revoked_idx'),
        ),
    ]
