# Generated by Django 5.0.6 on 2026-05-20 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.BinaryField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tenancy.customeruser')),
            ],
            options={
                'db_table': 'customer_session',
                'indexes': [models.Index(fields=['expires_at'], name='session_expires_idx')],
            },
        ),
    ]
