# Generated by Django 5.0.6 on 2026-05-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_customersession'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='apikey_customer_revoked_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_status_idx',
        ),
    ]
