# Generated by Django 5.0.6 on 2026-05-20 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=500)),
                ('request_hash', models.BinaryField()),
                ('response_status', models.SmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'idempotency_key',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(max_length=128, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('signature_valid', models.BooleanField()),
                ('payload_sha256', models.BinaryField()),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('accepted', 'Accepted'), ('rejected_signature', 'Rejected Signature'), ('rejected_stale', 'Rejected Stale'), ('duplicate', 'Duplicate'), ('error', 'Error')], max_length=24)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'webhook_delivery',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(choices=[('staff', 'Staff'), ('system', 'System'), ('customer', 'Customer')], max_length=16)),
                ('actor_id', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField()),
                ('reason', models.TextField(blank=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['resource_type', 'resource_id', '-created_at'], name='audit_resource_idx'), models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['actor_type', 'actor_id'], name='audit_actor_idx')],
            },
        ),
    ]
