# Generated by Django 5.0.6 on 2026-05-20 21:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_micro_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField()),
                ('issued_by_staff_id', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=255)),
                ('units_consumed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('event_timestamp', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=16)),
                ('total_micro_cents', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_delivery_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('usage', 'Usage'), ('credit_application', 'Credit Application'), ('adjustment', 'Adjustment')], max_length=24)),
                ('description', models.CharField(max_length=500)),
                ('units', models.BigIntegerField(default=0)),
                ('unit_price_micro_cents', models.BigIntegerField(default=0)),
                ('amount_micro_cents', models.BigIntegerField()),
                ('tier_ordinal', models.SmallIntegerField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'line_item',
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'price_plan',
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_unit', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_unit', models.BigIntegerField(blank=True, null=True)),
                ('unit_price_micro_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ordinality', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'price_tier',
                'ordering': ['price_plan', 'ordinality'],
            },
        ),
        migrations.CreateModel(
            name='UsageWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('units_consumed', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('event_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('last_recomputed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usage_window',
            },
        ),
    ]
