# Generated by Django 5.0.6 on 2026-05-20 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credits', to='tenancy.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='tenancy.apikey'),
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='tenancy.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='tenancy.customer'),
        ),
        migrations.AddField(
            model_name='credit',
            name='applied_to_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applied_credits', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='line_items', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='pricetier',
            name='price_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='billing.priceplan'),
        ),
        migrations.AddField(
            model_name='usagewindow',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usage_windows', to='tenancy.customer'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['customer', '-event_timestamp'], name='event_customer_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['api_key', '-event_timestamp'], name='event_apikey_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('adjusted_at__isnull', True), ('is_late', True)), fields=['customer'], name='event_late_unadj_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('request_id',), name='event_request_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('units_consumed__gte', 0)), name='event_units_nonneg'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'period_end'], name='invoice_status_period_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-period_start'], name='invoice_customer_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('customer', 'period_start'), name='invoice_unique_customer_period'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('total_micro_cents__gte', 0)), name='invoice_total_nonneg'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(condition=models.Q(('applied_to_invoice__isnull', True)), fields=['customer'], name='credit_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('customer', 'idempotency_key'), name='credit_unique_idemp'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.CheckConstraint(check=models.Q(('amount_micro_cents__gt', 0)), name='credit_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['invoice'], name='lineitem_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricetier',
            constraint=models.UniqueConstraint(fields=('price_plan', 'start_unit'), name='price_tier_unique_start'),
        ),
        migrations.AddConstraint(
            model_name='pricetier',
            constraint=models.CheckConstraint(check=models.Q(('end_unit__isnull', True), ('end_unit__gt', models.F('start_unit')), _connector='OR'), name='price_tier_end_gt_start'),
        ),
        migrations.AddConstraint(
            model_name='pricetier',
            constraint=models.CheckConstraint(check=models.Q(('unit_price_micro_cents__gte', 0)), name='price_tier_nonneg_price'),
        ),
        migrations.AddIndex(
            model_name='usagewindow',
            index=models.Index(fields=['customer', '-window_start'], name='window_customer_start_idx'),
        ),
        migrations.AddIndex(
            model_name='usagewindow',
            index=models.Index(condition=models.Q(('sealed_at__isnull', True)), fields=['window_start'], name='window_unsealed_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagewindow',
            constraint=models.UniqueConstraint(fields=('customer', 'window_start'), name='window_unique_customer_start'),
        ),
    ]
