# Generated by Django 5.0.6 on 2026-05-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronState',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cron_state',
            },
        ),
    ]
