# Generated by Django 5.0.6 on 2026-05-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_cronstate'),
        ('tenancy', '0002_customersession'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_request_id_unique',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('customer', 'request_id'), name='event_customer_request_id_unique'),
        ),
    ]
