# Generated by Django 5.0.6 on 2026-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_event_event_request_id_unique_and_more'),
        ('tenancy', '0003_remove_apikey_apikey_customer_revoked_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lineitem',
            name='lineitem_invoice_idx',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gt', models.F('period_start'))), name='invoice_period_end_gt_start'),
        ),
    ]
