# Generated by Django 5.0.6 on 2026-05-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_lineitem_lineitem_invoice_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_customer_period_idx',
        ),
    ]
